[package]
name = "upcrb"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
clap = { version = "4.5.4", features = ["derive"] }
urlencoding = "2.1.3"
